apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tile38-prom-service-monitor-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "tile38.name" . }}
      release: {{ .Release.Name }}
      role: prometheus
  endpoints:
  - port: prom
